### ISSUE TITLE
It removed all styles except those in the spreadsheet, and also removed styles from every object

### ISSUE THREAD

**Issue by TrevorColeman** [nolastan/sync.sketchplugin#8] opened 2016-01-27 23:35 UTC
Hey there,

Used the plug-in, and it seems useful except for the following:
1. When I ran the plugin for the first time it removed all of the styles I had created in the document. A LOT of styes.A warning would have been nice. 
2. Whenever I run the plugin, it removes the styles from every object. So if I style a text box H1, then run the plugin, it will show as "no text style" (along with every other element in the document.)  is the plugin supposed to update the styles, or remove them?

I feel like a bit more description in the readme could prevent this confusion. The behaviour could be useful, but the word "sync" suggests something else, and I was pretty surprised.

**Comment by nolastan** [comment] 2016-02-05 00:08
Thanks for the feedback.
1. This functionality is described in the second line of the readme, but I can add a notice in the plugin window as well to be more clear since not everyone will read the readme.
2. This sounds like a duplicate of https://github.com/nolastan/sync.sketchplugin/issues/7.

**Comment by nolastan** [comment] 2016-02-05 00:12
Perhaps this would be more clear?
![image](https://cloud.githubusercontent.com/assets/727778/12834129/112bc4ba-cb5a-11e5-800f-f2ad2d1a62ec.png)

**Closed as completed** 2016-02-05 01:06 UTC

**Comment by TrevorColeman** [comment] 2016-02-07 00:47
I think it's not just that they will be replaced -- any styles not in the current document will be removed/destroyed.

For instance, I didn't create any shared styles for objects in the google sheet, and this wiped out my entire list.

I would say something like: 

> This will delete all existing text styles, objects styles, and global colors and replace them with the contents of the google sheet.

The language you have above still doesn't adequately capture the fact that the action doesn't just overwrite styles with the same name, but removes every single style, whether they are in the google sheet or not.
