### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by getflourish** [nolastan/sync.sketchplugin#30] opened 2017-01-18 17:23 UTC
I think it would be great if the text styles would be sorted by name or font size. So far, I don’t see any sorting? I might make a PR for this though ;)

![screen shot 2017-01-18 at 18 22 06](https://cloud.githubusercontent.com/assets/183989/22075152/208c839a-ddab-11e6-8308-964e7277629e.png)

**Comment by nolastan** [comment] 2017-01-18 20:29
The text styles appear to be sorted by name for me.

**Comment by nolastan** [comment] 2017-02-13 02:36
Closing since I cannot reproduce the issue. Feel free to re-open with steps to reproduce. Thanks!

**Closed as completed by nolastan** 2017-02-13 02:36 UTC
